# -*- coding: utf-8 -*-
"""Copy of Applied_Tech_Project_2_Question_copy_v1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpaczGcv0ktcPrRKFpr_np4OhPp1QX7-

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

1. Variables and Data-types.

2. While Loop, Data-Type Conversion and Conditional Statements.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1b6kJOJ8XFpXrKbvBjjcXAHTGBQcT6TUn

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project2** format.

4. Now, write your code in the prescribed code cells.

---

#### Activity 1: Natural Numbers from 2011 - 2021

Here you need to print all the natural numbers from 2011 - 2021 (including both 2011 and 2021) using a `while` loop.

Follow the steps given below to achieve the desired result:

- **Step 1**: Store the starting number i.e. `2011` in a variable `num`.

- **Step 2**: Define the condition for `while` loop. This loop must be executed till the value stored in variable `num` is less than or equal to `2021`. So the condition for `while` loop will be `while(num)<=2021`.

- **Step 3**: Inside the `while` loop, first print the value stored in `num` variable, then increment the value of `num` by `1` to print the next consecutive number.
"""

# Natural Numbers from 2011 - 2021 using while loop
num = 2011
while(num)<=2021:
  num = num+1

"""---

#### Activity 2: Football Points

Get the number of `wins` of a football team as an input. Write a program to calculate the total number of win points the football team has obtained so far.

Every single win gains `3` points to the team.

<center><img src='https://i.imgur.com/baU8P6A.png' width =370/></center>



**Example**:

```
Sample Input:

            Enter the number of matches won by the football team: 5

Sample Output:

            The total number of points for the team is 15
```

**Note**: The value of `win` should be greater than or equal to `0`.

Follow the steps given below to achieve the desired result:

- **Step 1**: Ask the user to enter the number of matches won by the football team using `input()` function and convert it into integer using `int()` function. Store the user input in a variable `wins` as follows:

   `wins=int(input(" Enter the number of matches won by the football team:"))`
   
   
- **Step 2**: Calculate the points gained on winning the matches by multiplying the number of wins (stored in `wins` variable) by `3` using the `*` operator (as each win gives 3 points to the team). Store the result in a variable (lets say `win_points`)

- **Step 3**: Print the value stored in the variable `win_points`.
"""

# Write your code here
# Step 1: Get the number of wins of a football team as an integer. Store it in a variable 'wins'
wins = int(input("Enter the ammount of wins:"))

# Step 2: Calculate the win points by multiplying the number of wins by 3
win_points = wins*3

# Step 3: Print the value stored in variable 'win_points'
print("Total points:",win_points)

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project2**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project2** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""